name: Setup

description: Set up PHP and Composer

inputs:
  php-version:
    description: The PHP Version(s)
    required: true
  php-extensions:
    description: The PHP Extensions you want to install.
    required: false
    default: dom, curl, libxml, mbstring, zip, json, bcmath, tokenizer, ctype, openssl

runs:
  using: composite
  steps:
    - name: Get PHP Extension cache dir
      id: get-cache-hash
      run: echo hash=$(echo $PHP_EXTENSIONS | md5sum | awk '{print $1}' ) >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        extensions: ${{ inputs.php-extensions }}

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        key: php-extensions-${{ steps.get-cache-hash.hash }}

    - name: Cache PHP Extensions
      uses: actions/cache@v4
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Get Composer cache dir
      id: composer-cache-dir
      run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        key: composer-cache-${{ hashFiles('**/composer.lock') }}
        path: ${{ steps.composer-cache-dir.outputs.dir }}
        restore-keys: composer-cache-
