name: Tests

on:
  pull_request

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '8.4'
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, json, bcmath, tokenizer, ctype, openssl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2
          extensions: ${{ env.PHP_EXTENSIONS }}

      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          key: extension-cache-v1

      - name: Cache extensions
        uses: actions/cache@v4
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Get Composer cache dir
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: composer-cache-

      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Site Setup
        run: |
          cp .env.example .env
          php artisan key:generate
          yarn
          yarn run build

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test --compact
